---

name: "Keep Repo Active"
run-name: "Keep Repo Active"
permissions:
  contents: write

concurrency:
  group: heartbeat
  cancel-in-progress: true

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  push: {paths: [.github/workflows/heartbeat.yml]}
  schedule:
    - cron: "25 1 28 * *"

jobs:
  keep-repo-active:
    name: "Keep Repo Active"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: .
          skip_dirty_check: true
          commit_options: --allow-empty  
          commit_message: |
            Keep repo alive
